import { defineConfig } from 'tsdown';

export default defineConfig({
  entry: { index: 'src/index.ts' },
  format: ['esm'],
  target: 'node18',
  outDir: 'dist',
  clean: true,
  sourcemap: true,
  deps: {
    neverBundle: [
      '@ajgifford/keepwatching-common-server',
      '@ajgifford/keepwatching-types',
      'axios',
      'axios-retry',
      'body-parser',
      'cookie-parser',
      'cors',
      'cron-parser',
      'dotenv',
      'express',
      'express-async-handler',
      'express-rate-limit',
      'firebase-admin',
      'helmet',
      'multer',
      'mysql2',
      'node-cache',
      'node-cron',
      'nodemailer',
      'socket.io',
      'streaming-availability',
      'uuid',
      'winston',
      'winston-daily-rotate-file',
      'zod',
    ],
  },
});
