import { defineConfig } from 'tsup';

export default defineConfig({
  entry: ['src/index.ts'],
  format: ['esm'],
  target: 'node18',
  outDir: 'dist',
  clean: true,
  sourcemap: true,
  bundle: true,
  external: [
    '@ajgifford/keepwatching-common-server',
    '@ajgifford/keepwatching-types',
    /^node:.*/,
    'axios',
    'axios-retry',
    'body-parser',
    'cookie-parser',
    'cors',
    'cron-parser',
    'dotenv',
    'express',
    'express-async-handler',
    'express-rate-limit',
    'firebase-admin',
    'helmet',
    'https',
    'multer',
    'mysql2',
    'node-cache',
    'node-cron',
    'nodemailer',
    'socket.io',
    'streaming-availability',
    'uuid',
    'winston',
    'winston-daily-rotate-file',
    'zod',
    'knex',
  ],
});
