export const sampleMovies = JSON.stringify([
  {
    id: '1',
    title: 'Inception',
    description: 'A thief who steals secrets through dreams.',
    release_date: '2010-07-16',
    genres: ['Science Fiction'],
    duration: 148,
    image: 'https://via.placeholder.com/150',
    user_rating: 9,
    mpa_rating: 'PG-13',
    watched: 'Watched',
    streaming_service: 'Netflix',
    profile: { id: '1', name: 'Andy' },
  },
  {
    id: '2',
    title: 'The Dark Knight',
    description: 'Batman faces the Joker in Gotham City.',
    release_date: '2008-07-18',
    genres: ['Action'],
    duration: 152,
    image: 'https://via.placeholder.com/150',
    user_rating: 10,
    mpa_rating: 'PG-13',
    watched: 'Watched',
    streaming_service: 'Peacock',
    profile: { id: '1', name: 'Andy' },
  },
]);
