export const sampleShowsWithProfiles = JSON.stringify([
  {
    id: '1',
    title: 'Stranger Things',
    description: 'A group of kids uncover mysteries in their small town.',
    release_date: '2016-07-15',
    genres: ['Sci-Fi', 'Drama'],
    streaming_service: 'Netflix',
    image: 'https://via.placeholder.com/96?text=Stranger+Thingse&font=roboto',
    user_rating: 9,
    tv_parental_guidelines: 'TV-14',
    number_of_seasons: 4,
    total_episodes: 34,
    profile: { id: '1', name: 'Andy', watched: 'Watched' },
  },
  {
    id: '2',
    title: 'Breaking Bad',
    description: 'A chemistry teacher turned meth producer.',
    release_date: '2008-01-20',
    genres: ['Drama'],
    streaming_service: 'Netflix',
    image: 'https://via.placeholder.com/96?text=Breaking+Bad&font=roboto',
    user_rating: 10,
    tv_parental_guidelines: 'TV-MA',
    number_of_seasons: 5,
    total_episodes: 62,
    profile: { id: '1', name: 'Andy', watched: 'Not Watched' },
  },
  {
    id: '3',
    title: 'The Office',
    description: 'A comedic look at office life.',
    genres: ['Comedy'],
    streaming_service: 'Peacock',
    image: 'https://via.placeholder.com/96?text=The+Office&font=roboto',
    profile: { id: '3', name: 'Adults', watched: 'Watched' },
  },
  {
    id: '4',
    title: 'The Mandalorian',
    description: 'A bounty hunter in the Star Wars universe.',
    genres: ['Sci-Fi', 'Action'],
    streaming_service: 'Disney+',
    image: 'https://via.placeholder.com/96?text=The+Madalorain&font=roboto',
    profile: { id: '4', name: 'Ben', watched: 'Watching' },
  },
  {
    id: '5',
    title: 'Parks and Recreation',
    description: 'The quirky employees of Pawnee, Indiana.',
    genres: ['Comedy'],
    streaming_service: 'Peacock',
    image: 'https://via.placeholder.com/96?text=Parks+and+Rec&font=roboto',
    profile: { id: '3', name: 'Adults', watched: 'Watched' },
  },
]);

export const sampleShows = JSON.stringify([
  {
    id: '1',
    title: 'Stranger Things',
    description: 'A group of kids uncover mysteries in their small town.',
    release_date: '2016-07-15',
    genre: 'Science Fiction',
    image: 'https://via.placeholder.com/150',
    user_rating: 9,
    tv_parental_guidelines: 'TV-14',
    number_of_seasons: 4,
    total_episodes: 34,
  },
  {
    id: '2',
    title: 'Breaking Bad',
    description: 'A chemistry teacher turned meth producer.',
    release_date: '2008-01-20',
    genre: 'Drama',
    image: 'https://via.placeholder.com/150',
    user_rating: 10,
    tv_parental_guidelines: 'TV-MA',
    number_of_seasons: 5,
    total_episodes: 62,
  },
]);

export const sampleShows_2 = JSON.stringify([
  {
    id: '3',
    title: 'Real Housewifes of Beverly Hills',
    description: 'A group of kids uncover mysteries in their small town.',
    release_date: '2016-07-15',
    genre: 'Science Fiction',
    image: 'https://via.placeholder.com/150',
    user_rating: 9,
    tv_parental_guidelines: 'TV-14',
    number_of_seasons: 4,
    total_episodes: 34,
  },
  {
    id: '4',
    title: 'First 48',
    description: 'A chemistry teacher turned meth producer.',
    release_date: '2008-01-20',
    genre: 'Drama',
    image: 'https://via.placeholder.com/150',
    user_rating: 10,
    tv_parental_guidelines: 'TV-MA',
    number_of_seasons: 5,
    total_episodes: 62,
  },
]);

export const sampleShows_3 = JSON.stringify([
  {
    id: '6',
    title: 'Bluey',
    description: 'A group of kids uncover mysteries in their small town.',
    release_date: '2016-07-15',
    genre: 'Science Fiction',
    image: 'https://via.placeholder.com/150',
    user_rating: 9,
    tv_parental_guidelines: 'TV-14',
    number_of_seasons: 4,
    total_episodes: 34,
  },
  {
    id: '7',
    title: 'Paw Patrol',
    description: 'A chemistry teacher turned meth producer.',
    release_date: '2008-01-20',
    genre: 'Drama',
    image: 'https://via.placeholder.com/150',
    user_rating: 10,
    tv_parental_guidelines: 'TV-MA',
    number_of_seasons: 5,
    total_episodes: 62,
  },
]);

export const sampleShow = JSON.stringify({
  id: '1',
  title: 'Stranger Things',
  description: 'A group of kids uncover mysteries in their small town.',
  release_date: '2016-07-15',
  genre: 'Science Fiction',
  image: 'https://via.placeholder.com/150',
  user_rating: 9,
  tv_parental_guidelines: 'TV-14',
  number_of_seasons: 4,
  total_episodes: 34,
  streaming_service: 'Netflix',
  seasons: [
    {
      id: 1,
      title: 'Season 1',
      number_of_episodes: 3,
      release_date: '2022-01-01',
      image: 'https://via.placeholder.com/150',
      episodes: [
        {
          id: 101,
          title: 'The Vanishing of Will Byers',
          episode_number: '101',
          summary: 'When Will Byers goes missing his friends investigate',
          release_date: '2022-01-01',
          duration: '42m',
          image: 'https://via.placeholder.com/100',
          watched: false,
        },
        {
          id: 102,
          title: 'The Weirdo on Maple Street',
          episode_number: '102',
          summary: 'A new kid moves into the house on Maple Street',
          release_date: '2022-01-08',
          duration: '45m',
          image: 'https://via.placeholder.com/100',
          watched: false,
        },
        {
          id: 103,
          title: 'Episode 3',
          episode_number: '103',
          release_date: '2022-01-15',
          duration: '40m',
          image: 'https://via.placeholder.com/100',
          watched: false,
        },
      ],
    },
    {
      id: 2,
      title: 'Season 2',
      number_of_episodes: 2,
      release_date: '2023-01-01',
      image: 'https://via.placeholder.com/150',
      episodes: [
        {
          id: 201,
          title: 'Episode 1',
          episode_number: '201',
          release_date: '2023-01-01',
          duration: '50m',
          image: 'https://via.placeholder.com/100',
          watched: false,
        },
        {
          id: 202,
          title: 'Episode 2',
          episode_number: '201',
          release_date: '2023-01-08',
          duration: '55m',
          image: 'https://via.placeholder.com/100',
          watched: false,
        },
      ],
    },
  ],
});

export const sampleSeasons = JSON.stringify([
  {
    id: '1',
    show_id: '1',
    title: 'Season 1',
    number_of_episodes: 8,
  },
  {
    id: '2',
    show_id: '1',
    title: 'Season 2',
    number_of_episodes: 9,
  },
  {
    id: '3',
    show_id: '2',
    title: 'Season 1',
    number_of_episodes: 7,
  },
]);

export const sampleEpisodes = JSON.stringify([
  {
    id: '1',
    season_id: '1',
    title: 'The Vanishing of Will Byers',
    duration: 47,
    episode_number: 1,
  },
  {
    id: '2',
    season_id: '1',
    title: 'The Weirdo on Maple Street',
    duration: 55,
    episode_number: 2,
  },
  {
    id: '3',
    season_id: '2',
    title: 'Madmax',
    duration: 48,
    episode_number: 1,
  },
]);
